@API_HostAddress = https://localhost:7052

POST {{API_HostAddress}}/Authorization/Login
Content-Type: application/json

{
  //LoginRequestModel
}

###

GET {{API_HostAddress}}/Tableau

###

POST {{API_HostAddress}}/Terminal/Stamp
Content-Type: application/json

{
  //StampType
}

###

POST {{API_HostAddress}}/Terminal/Stamp/0
Content-Type: application/json

{
  //StampType
}

###
